### ISSUE TITLE
Photo ilustration

### ISSUE THREAD

**Issue by GLlgGL** [GabrielL92I/OpenVPNonMikrotik#1]
![BridgeMikrotikVPN](https://user-images.githubusercontent.com/44748406/192095424-419f230b-a815-4f8e-9ee6-553b7cc6f7d7.png)

**Comment by GLlgGL** [comment]
![NetworkAddess](https://user-images.githubusercontent.com/44748406/192097740-679f4df2-b144-416e-ba6c-08247b2cd722.png)

**Comment by GLlgGL** [comment]
![IPPOOL](https://user-images.githubusercontent.com/44748406/192097055-2a06074c-a66a-48a7-9ef4-022a829135a5.png)

**Comment by GabrielL92I** [comment]
![IPDHCP](https://user-images.githubusercontent.com/44748406/192096956-fbd7e18f-1edd-498c-84b1-331d1e703560.png)

**Comment by GabrielL92I** [comment]
![IPDHCPSERVER](https://user-images.githubusercontent.com/44748406/192097000-25147c4a-a62e-445a-a22b-682e6f744eab.png)

**Comment by GLlgGL** [comment]
![IPFILTERRULES](https://user-images.githubusercontent.com/44748406/192097762-349de4da-9a68-4963-b814-3b333d9c7eae.png)

**Comment by GLlgGL** [comment]
![NATRULE](https://user-images.githubusercontent.com/44748406/192098130-ac7b040a-7afe-4d5c-94d7-da9df854b818.png)

**Comment by GLlgGL** [comment]
![Certificatescreation](https://user-images.githubusercontent.com/44748406/192099452-94fbe97e-a68a-44ad-b6f2-442fb5ff0f8f.png)

**Comment by GLlgGL** [comment]
![exportcertificates](https://user-images.githubusercontent.com/44748406/192100024-4636e14b-fa4b-47e8-b5e2-a03470c115dc.png)

**Comment by GLlgGL** [comment]
![OVPNSERVER](https://user-images.githubusercontent.com/44748406/192100634-bdc14c96-2590-465c-8120-3451949f4be0.png)

**Comment by GLlgGL** [comment]
![Profile](https://user-images.githubusercontent.com/44748406/192100861-1827ca05-caa7-4196-8253-9d06d294e578.png)

**Comment by GabrielL92I** [comment]
![networks](https://user-images.githubusercontent.com/44748406/192100997-b36564ed-1b6c-4452-a7ba-a83b59b1980d.png)

**Comment by GLlgGL** [comment]
![secret](https://user-images.githubusercontent.com/44748406/192101298-28a028e6-b370-4722-b022-2daa3c806b08.png)

**Comment by GLlgGL** [comment]
![filess](https://user-images.githubusercontent.com/44748406/192105096-ed4960b0-3273-40ec-a1fa-fd71bd796157.png)

**Comment by GLlgGL** [comment]
![connected](https://user-images.githubusercontent.com/44748406/192104965-dc0d7c5a-e10e-49dd-92c3-867192aec85a.png)
